Fix encoding problem reading changelog
The Unicode `…` characters cause a problem on some environments when
pip installing.  Probably locale specific, since the default
encoding used by `open` depends on the locale.  Now explicity set it
to UTF-8.

```
Processing /path/to/katportalclient
  Running setup.py (path:/tmp/pip-dqxy93lt-build/setup.py) egg_info for package from file:///path/to/katportalclient
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-dqxy93lt-build/setup.py", line 18, in <module>
        file_contents = _f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5094: ordinal not in range(128)
```